/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vnxszrwj5jberpnzqxyepdr2nm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2sweohsnczhyxctzh6qk5ng244",
    "aws_cognito_identity_pool_id": "us-east-1:bb915904-691b-4771-9357-3005d58ab61e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gkPxRMwrK",
    "aws_user_pools_web_client_id": "m9356tcq8cu3sfe236g360tqt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "deliverybairrocom-storage155845-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
